version: "3.8"
services:
  minecraft-overviewer:
    image: minecraft-overviewer-autorender:0.2.1
    volumes:
      - ./world:/world:ro
      - render-result:/render
    tmpfs:
      - /cache:size=4G,uid=1000
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '4.00'
          memory: 4G
  reverse-proxy:
    image: caddy:2.6.2-alpine
    depends_on:
      - minecraft-overviewer
    volumes:
      - render-result:/render:ro
    entrypoint: ["caddy", "file-server", "--root", "/render", "--listen", ":25666"]
    ports:
      - 25666:25666
    deploy:
      mode: replicated
      replicas: 1

volumes:
  render-result:
